apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hhmk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-hhmk@sha256:c069118f4199b81aa7b7b1ebc0a6917ad3c56a8167c33300b907c2c8423deefa
        name: my-nodejs
        resources: {}
status: {}
